AutoCheckTicketSystem/AutoCheckTicketSystem/Models/Metadata/TypeTicket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AutoCheckTicketSystem.Models.Metadata
{
    public class TypeTicket
    {
        [Key]
        public int TypeID { get; set; }
        [Display(Name = "Loại vé")]
        public string TypeName { get; set; }
        [Display(Name = "Giá tiền")]
        public int Price { get; set; }

        public ICollection<Card> Cards { get; set; }
        public ICollection<Transaction> Tickets { get; set; }
    }
}

AutoCheckTicketSystem/AutoCheckTicketSystem/Controllers/TypeTicketController.cs
using AutoCheckTicketSystem.Models.Metadata;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoCheckTicketSystem.Controllers
{
    public class TypeTicketController : Controller
    {
        WebAppContext db = new WebAppContext();

        // GET: TypeTicket
        public ActionResult Index()
        {
            return View(db.type.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TypeTicket type)
        {
            //them vao co so du lieu.
            if (ModelState.IsValid)
            {
                db.type.Add(type);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int TypeID)
        {
            TypeTicket type = db.type.Where(x => x.TypeID == TypeID).SingleOrDefault();
            if (type == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(type);
        }

        [HttpPost]
        public ActionResult Edit(TypeTicket type)
        {
            if (ModelState.IsValid)
            {
                //cập nhật.
                db.Entry(type).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public ActionResult Delete(int TypeID)
        {
            TypeTicket type = db.type.Where(x => x.TypeID == TypeID).SingleOrDefault();
            db.type.Remove(type);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AutoCheckTicketSystem/AutoCheckTicketSystem/Controllers/UserController.cs
using AutoCheckTicketSystem.Models.Metadata;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoCheckTicketSystem.Controllers
{
    public class UserController : Controller
    {
        WebAppContext db = new WebAppContext();
        // GET: /User/
        public ActionResult Index()
        {
            var listUser = db.employee.Where(x=>x.IsUsed == true).ToList();
            return View(listUser);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Employee user, HttpPostedFileBase fileUpload)
        {
            //them vao co so du lieu.
            if (ModelState.IsValid)
            {
                //luu ten cua file.
                var fileName = Path.GetFileName(fileUpload.FileName);
                //luu duong dan cua file.
                var path = Path.Combine(Server.MapPath("~/Content/CssAdmin/img"), fileName);
                //kiem tra hinh anh da ton tai chua.
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                user.ImageID = fileUpload.FileName;
                user.IsUsed = true;
                db.employee.Add(user);
                db.SaveChanges();
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int EmployeeID)
        {
            Employee user = db.employee.Where(x => x.EmployeeID == EmployeeID).SingleOrDefault();
            if(user == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.ImageID = user.ImageID;
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(Employee user)
        {
            if(ModelState.IsValid)
            {
                //cập nhật.
                db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public ActionResult Delete(int EmployeeID)
        {
            Employee user = db.employee.Where(x => x.EmployeeID == EmployeeID).SingleOrDefault();
            user.IsUsed = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public string ProcessUpload(HttpPostedFileBase file)
        {

            file.SaveAs(Server.MapPath("~/Content/CssAdmin/img/" + file.FileName));
            return "/Content/CssAdmin/img/" + file.FileName;
        }
	}
}

AutoCheckTicketSystem/AutoCheckTicketSystem/Views/TypeTicket/Create.cshtml
@model AutoCheckTicketSystem.Models.Metadata.TypeTicket

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

<div id="content" class="span10">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <a href="index.html">Type Ticket</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Create</a></li>
    </ul>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon list"></i><span class="break"></span>Tickets</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <div class="box span12">
                            <h4>Type Ticket</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger"})

                            <div class="form-group">
                                @Html.LabelFor(model => model.TypeName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10 marginLeft">
                                    @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TypeName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
                                <div class="col-md-10 marginLeft">
                                    @Html.EditorFor(model => model.Price)
                                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
</div>


@*<div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Nhập thông tin người dùng
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @using (Html.BeginForm("Edit", "User", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(model => model.EmployeeID)
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-3" })

                                    @Html.TextBoxFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })

                                </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Identity, htmlAttributes: new { @class = "control-label col-md-3" })

                                        @Html.TextBoxFor(model => model.Identity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Identity, "", new { @class = "text-danger" })

                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-3" })

                                        @Html.TextBoxFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })

                                    </div>


                                    <div class="form-group">
                                        @Html.LabelFor(model => model.IsUsed, htmlAttributes: new { @class = "control-label col-md-3" })


                                        @Html.CheckBoxFor(model => model.IsUsed)
                                        @Html.ValidationMessageFor(model => model.IsUsed, "", new { @class = "text-danger" })


                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-3" })

                                        @Html.TextBoxFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })

                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Cập nhật" class="btn btn-default" />
                                        </div>
                                    </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@

AutoCheckTicketSystem/AutoCheckTicketSystem/Views/TypeTicket/Edit.cshtml
@model AutoCheckTicketSystem.Models.Metadata.TypeTicket

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

<div id="content" class="span10">
    <h2>Chỉnh sửa thông tin loại vé</h2>
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li>
            <a href="index.html">Type Ticket</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Edit</a></li>
    </ul>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon list"></i><span class="break"></span>Tickets</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                @using (Html.BeginForm("Edit", "TypeTicket", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <div class="box span12">
                            <h4>Type Ticket</h4>
                            <hr />
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.TypeID)

                            <div class="form-group">
                                @Html.LabelFor(model => model.TypeName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10 marginLeft">
                                    @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TypeName)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
                                <div class="col-md-10 marginLeft">
                                    @Html.EditorFor(model => model.Price)
                                    @Html.ValidationMessageFor(model => model.Price)
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-6">
                                    <input type="submit" value="Lưu" class="btn btn-default" />
                                </div>
                                <div class="col-md-offset-2 col-md-6">
                                    <input type="submit" value="Hủy" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
</div>


@*<div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Nhập thông tin người dùng
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @using (Html.BeginForm("Edit", "User", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(model => model.EmployeeID)
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-3" })

                                    @Html.TextBoxFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })

                                </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Identity, htmlAttributes: new { @class = "control-label col-md-3" })

                                        @Html.TextBoxFor(model => model.Identity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Identity, "", new { @class = "text-danger" })

                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-3" })

                                        @Html.TextBoxFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })

                                    </div>


                                    <div class="form-group">
                                        @Html.LabelFor(model => model.IsUsed, htmlAttributes: new { @class = "control-label col-md-3" })


                                        @Html.CheckBoxFor(model => model.IsUsed)
                                        @Html.ValidationMessageFor(model => model.IsUsed, "", new { @class = "text-danger" })


                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-3" })

                                        @Html.TextBoxFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })

                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Cập nhật" class="btn btn-default" />
                                        </div>
                                    </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@

AutoCheckTicketSystem/AutoCheckTicketSystem/Views/TypeTicket/Index.cshtml
@using AutoCheckTicketSystem.Models.Metadata;
@model List<TypeTicket>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

<div id="content" class="span10">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="index.html">Home</a>
            <i class="icon-angle-right"></i>
        </li>
        <li><a href="#">Type Ticket</a></li>
    </ul>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon list"></i><span class="break"></span>Tickets</h2>
                <div class="box-icon">
                    <a href="/TypeTicket/Create"><i class="halflings-icon plus"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                </div>
            </div>
            
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable datatable">
                    <thead>
                        <tr>
                            <th>Loại vé</th>
                            <th>Giá tiền</th>
                            <th>Mô tả</th>
                            <th>Tác vụ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr id="row_@item.TypeID">
                                <td>@item.TypeName</td>
                                <td class="center">@item.Price</td>
                                <td class="center">Mô tả thông tin loại vé</td>
                                <td class="center">
                                    @Html.ActionLink("Chỉnh Sửa", "Edit", new { @TypeID = item.TypeID }) |
                                    @Ajax.ActionLink("Xóa", "Delete", new { @TypeID = item.TypeID }, new AjaxOptions
                               {
                                   Confirm = "Bạn có muốn xoá bản ghi này?",
                                   OnComplete = "$('#row_" + @item.TypeID + "').remove()",
                                   HttpMethod = "Delete"
                               })
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div><!--/span-->

    </div><!--/row-->
</div><!--/.fluid-container-->